// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblModulesModel
{
    public int Id { get; set; }
    [Column(TypeName = "VARCHAR(MAX)")]
    public string? Title { get; set; }
    [Column(TypeName = "VARCHAR(MAX)")]
    public string? Img { get; set; }
    [Column(TypeName = "VARCHAR(MAX)")]
    public string? Link { get; set; }
    [Column(TypeName = "VARCHAR(MAX)")]
    public string? Class { get; set; }
    public int? Status { get; set; }
    //

}